"""add address_id and creator_name columsn in user_workout_plans table and remove template_id

Revision ID: 072fe86ce200
Revises: 35a8b84dca70
Create Date: 2026-01-08 21:13:16.837451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '072fe86ce200'
down_revision: Union[str, Sequence[str], None] = '35a8b84dca70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
