"""add remove start_date and end_date in user_workout_plans and last_performed_date in user_progress tables

Revision ID: 0a3301eed8b2
Revises: 5b809db4e7ee
Create Date: 2026-01-18 20:02:36.357344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3301eed8b2'
down_revision: Union[str, Sequence[str], None] = '5b809db4e7ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'last_performed_date')
    op.drop_column('user_workout_plans', 'end_date')
    op.drop_column('user_workout_plans', 'start_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workout_plans', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('user_workout_plans', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_progress', sa.Column('last_performed_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
