"""Initial tables

Revision ID: 0d747c475f91
Revises: 
Create Date: 2025-12-27 20:49:36.823242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d747c475f91'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tutorial_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('ml_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('training_data_until', sa.Date(), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('membership_status', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('target_muscle_groups', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_templates_name'), 'workout_templates', ['name'], unique=False)
    op.create_table('body_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_pct', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('muscle_mass_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('chest_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('waist_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('hips_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_measurement_date', 'body_measurements', ['user_id', 'measurement_date'], unique=False)
    op.create_index(op.f('ix_body_measurements_measurement_date'), 'body_measurements', ['measurement_date'], unique=False)
    op.create_index(op.f('ix_body_measurements_user_id'), 'body_measurements', ['user_id'], unique=False)
    op.create_table('template_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('sets_range_min', sa.Integer(), nullable=True),
    sa.Column('sets_range_max', sa.Integer(), nullable=True),
    sa.Column('reps_range_min', sa.Integer(), nullable=True),
    sa.Column('reps_range_max', sa.Integer(), nullable=True),
    sa.Column('rest_seconds_min', sa.Integer(), nullable=True),
    sa.Column('rest_seconds_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_exercises_exercise_id'), 'template_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_template_exercises_template_id'), 'template_exercises', ['template_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('primary_goal', sa.String(length=100), nullable=True),
    sa.Column('experience_months', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('one_rep_max_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('training_volume_kg', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('personal_record_date', sa.Date(), nullable=True),
    sa.Column('last_performed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_exercise', 'user_progress', ['user_id', 'exercise_id'], unique=False)
    op.create_index(op.f('ix_user_progress_exercise_id'), 'user_progress', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('user_workout_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_regular', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_status', 'user_workout_plans', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_workout_plans_user_id'), 'user_workout_plans', ['user_id'], unique=False)
    op.create_table('scheduled_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_plan_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['user_workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plan_scheduled_date', 'scheduled_workouts', ['workout_plan_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_scheduled_workouts_workout_plan_id'), 'scheduled_workouts', ['workout_plan_id'], unique=False)
    op.create_table('exercise_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_workout_id', sa.UUID(), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('recommended_sets', sa.Integer(), nullable=True),
    sa.Column('recommended_reps', sa.Integer(), nullable=True),
    sa.Column('recommended_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_created_at', 'exercise_recommendations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_exercise_recommendations_user_id'), 'exercise_recommendations', ['user_id'], unique=False)
    op.create_table('scheduled_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scheduled_workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('planned_sets', sa.Integer(), nullable=True),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('planned_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('planned_rest_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scheduled_workout_order', 'scheduled_exercises', ['scheduled_workout_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_scheduled_exercises_scheduled_workout_id'), 'scheduled_exercises', ['scheduled_workout_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_workout_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_start_time', 'workout_sessions', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('session_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_order', 'session_exercises', ['workout_session_id', 'sequence_order'], unique=False)
    op.create_index(op.f('ix_session_exercises_workout_session_id'), 'session_exercises', ['workout_session_id'], unique=False)
    op.create_table('workout_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('planned_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('actual_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('planned_reps', sa.Integer(), nullable=True),
    sa.Column('completed_reps', sa.Integer(), nullable=True),
    sa.Column('rest_seconds_actual', sa.Integer(), nullable=True),
    sa.Column('rpe_score', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_exercise_set', 'workout_sets', ['session_exercise_id', 'set_number'], unique=False)
    op.create_index(op.f('ix_workout_sets_session_exercise_id'), 'workout_sets', ['session_exercise_id'], unique=False)
    op.create_table('ml_training_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('workout_session_id', sa.UUID(), nullable=False),
    sa.Column('session_exercise_id', sa.UUID(), nullable=True),
    sa.Column('workout_set_id', sa.UUID(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fitness_level', sa.String(length=50), nullable=True),
    sa.Column('primary_goal', sa.String(length=100), nullable=True),
    sa.Column('experience_months', sa.Integer(), nullable=True),
    sa.Column('current_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('current_body_fat_pct', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('bmi', sa.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('muscle_group', sa.String(length=100), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('exercise_difficulty', sa.String(length=50), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=20), nullable=True),
    sa.Column('session_energy_level', sa.Integer(), nullable=True),
    sa.Column('session_mood', sa.String(length=50), nullable=True),
    sa.Column('days_since_last_workout', sa.Integer(), nullable=True),
    sa.Column('total_session_duration_min', sa.Integer(), nullable=True),
    sa.Column('planned_sets', sa.Integer(), nullable=True),
    sa.Column('planned_reps_per_set', sa.Integer(), nullable=True),
    sa.Column('planned_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('completed_sets', sa.Integer(), nullable=True),
    sa.Column('completed_reps_per_set', sa.Integer(), nullable=True),
    sa.Column('actual_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('completion_rate', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('average_rpe', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('total_volume_kg', sa.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('rpe_increase_per_set', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('rep_decrease_per_set', sa.Integer(), nullable=True),
    sa.Column('exercise_was_appropriate', sa.Boolean(), nullable=True),
    sa.Column('next_recommended_sets', sa.Integer(), nullable=True),
    sa.Column('next_recommended_reps', sa.Integer(), nullable=True),
    sa.Column('next_recommended_weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_type', sa.String(length=100), nullable=True),
    sa.Column('feedback_comments', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('data_quality_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('is_training_ready', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.ForeignKeyConstraint(['workout_set_id'], ['workout_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_extraction_date', 'ml_training_data', ['created_at'], unique=False)
    op.create_index('idx_training_ready', 'ml_training_data', ['is_training_ready', 'data_quality_score'], unique=False)
    op.create_index('idx_user_exercise_date', 'ml_training_data', ['user_id', 'exercise_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_ml_training_data_exercise_id'), 'ml_training_data', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_ml_training_data_user_id'), 'ml_training_data', ['user_id'], unique=False)
    op.create_index(op.f('ix_ml_training_data_workout_session_id'), 'ml_training_data', ['workout_session_id'], unique=False)
    op.create_table('user_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=True),
    sa.Column('workout_set_id', sa.UUID(), nullable=True),
    sa.Column('feedback_type', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_set_id'], ['workout_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedback_user_id'), 'user_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedback_user_id'), table_name='user_feedback')
    op.drop_table('user_feedback')
    op.drop_index(op.f('ix_ml_training_data_workout_session_id'), table_name='ml_training_data')
    op.drop_index(op.f('ix_ml_training_data_user_id'), table_name='ml_training_data')
    op.drop_index(op.f('ix_ml_training_data_exercise_id'), table_name='ml_training_data')
    op.drop_index('idx_user_exercise_date', table_name='ml_training_data')
    op.drop_index('idx_training_ready', table_name='ml_training_data')
    op.drop_index('idx_extraction_date', table_name='ml_training_data')
    op.drop_table('ml_training_data')
    op.drop_index(op.f('ix_workout_sets_session_exercise_id'), table_name='workout_sets')
    op.drop_index('idx_session_exercise_set', table_name='workout_sets')
    op.drop_table('workout_sets')
    op.drop_index(op.f('ix_session_exercises_workout_session_id'), table_name='session_exercises')
    op.drop_index('idx_session_order', table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index('idx_user_start_time', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_scheduled_exercises_scheduled_workout_id'), table_name='scheduled_exercises')
    op.drop_index('idx_scheduled_workout_order', table_name='scheduled_exercises')
    op.drop_table('scheduled_exercises')
    op.drop_index(op.f('ix_exercise_recommendations_user_id'), table_name='exercise_recommendations')
    op.drop_index('idx_user_created_at', table_name='exercise_recommendations')
    op.drop_table('exercise_recommendations')
    op.drop_index(op.f('ix_scheduled_workouts_workout_plan_id'), table_name='scheduled_workouts')
    op.drop_index('idx_plan_scheduled_date', table_name='scheduled_workouts')
    op.drop_table('scheduled_workouts')
    op.drop_index(op.f('ix_user_workout_plans_user_id'), table_name='user_workout_plans')
    op.drop_index('idx_user_status', table_name='user_workout_plans')
    op.drop_table('user_workout_plans')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_exercise_id'), table_name='user_progress')
    op.drop_index('idx_user_exercise', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_template_exercises_template_id'), table_name='template_exercises')
    op.drop_index(op.f('ix_template_exercises_exercise_id'), table_name='template_exercises')
    op.drop_table('template_exercises')
    op.drop_index(op.f('ix_body_measurements_user_id'), table_name='body_measurements')
    op.drop_index(op.f('ix_body_measurements_measurement_date'), table_name='body_measurements')
    op.drop_index('idx_user_measurement_date', table_name='body_measurements')
    op.drop_table('body_measurements')
    op.drop_index(op.f('ix_workout_templates_name'), table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_table('ml_models')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
