"""update the workout_sets  tables

Revision ID: 141f2e73c974
Revises: 072fe86ce200
Create Date: 2026-01-09 19:22:24.591006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141f2e73c974'
down_revision: Union[str, Sequence[str], None] = '072fe86ce200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_workout_plans_address_id_fkey'), 'user_workout_plans', type_='foreignkey')
    op.add_column('workout_sets', sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True))
    op.add_column('workout_sets', sa.Column('reps', sa.Integer(), nullable=False))
    op.add_column('workout_sets', sa.Column('rest_seconds', sa.Integer(), nullable=True))
    op.drop_column('workout_sets', 'planned_weight_kg')
    op.drop_column('workout_sets', 'planned_reps')
    op.drop_column('workout_sets', 'rpe_score')
    op.drop_column('workout_sets', 'notes')
    op.drop_column('workout_sets', 'completed_reps')
    op.drop_column('workout_sets', 'rest_seconds_actual')
    op.drop_column('workout_sets', 'actual_weight_kg')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_sets', sa.Column('actual_weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('workout_sets', sa.Column('rest_seconds_actual', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workout_sets', sa.Column('completed_reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workout_sets', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('workout_sets', sa.Column('rpe_score', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.add_column('workout_sets', sa.Column('planned_reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('workout_sets', sa.Column('planned_weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.drop_column('workout_sets', 'rest_seconds')
    op.drop_column('workout_sets', 'reps')
    op.drop_column('workout_sets', 'weight_kg')
    op.create_foreign_key(op.f('user_workout_plans_address_id_fkey'), 'user_workout_plans', 'workout_templates', ['address_id'], ['id'])
    # ### end Alembic commands ###
