"""update workout_templates and template_exercises table in GoLlift_db database

Revision ID: 1d4569bc6281
Revises: 4332137f42a6
Create Date: 2026-01-02 14:45:46.601824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4569bc6281'
down_revision: Union[str, Sequence[str], None] = '4332137f42a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('target_musle', sa.String(length=100), nullable=True))
    op.alter_column('exercises', 'icon',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_exercises_body_part'), 'exercises', ['body_part'], unique=False)
    op.create_index(op.f('ix_exercises_target_musle'), 'exercises', ['target_musle'], unique=False)
    op.drop_column('exercises', 'target_muscle')
    op.add_column('template_exercises', sa.Column('workout_day', sa.String(length=50), nullable=True))
    op.add_column('template_exercises', sa.Column('exercise_name', sa.String(length=50), nullable=True))
    op.add_column('template_exercises', sa.Column('stage_of_exercises', sa.String(length=50), nullable=True))
    op.add_column('template_exercises', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('template_exercises', sa.Column('reps', sa.Integer(), nullable=True))
    op.add_column('template_exercises', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('template_exercises', sa.Column('rest_seconds', sa.Integer(), nullable=True))
    op.add_column('template_exercises', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('template_exercises', sa.Column('workout_type', sa.String(length=50), nullable=True))
    op.drop_column('template_exercises', 'sets_range_max')
    op.drop_column('template_exercises', 'rest_seconds_max')
    op.drop_column('template_exercises', 'sets_range_min')
    op.drop_column('template_exercises', 'rest_seconds_min')
    op.drop_column('template_exercises', 'reps_range_max')
    op.drop_column('template_exercises', 'reps_range_min')
    op.add_column('workout_templates', sa.Column('workout_type', sa.String(length=50), nullable=True))
    op.drop_column('workout_templates', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_templates', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('workout_templates', 'workout_type')
    op.add_column('template_exercises', sa.Column('reps_range_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('template_exercises', sa.Column('reps_range_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('template_exercises', sa.Column('rest_seconds_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('template_exercises', sa.Column('sets_range_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('template_exercises', sa.Column('rest_seconds_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('template_exercises', sa.Column('sets_range_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('template_exercises', 'workout_type')
    op.drop_column('template_exercises', 'notes')
    op.drop_column('template_exercises', 'rest_seconds')
    op.drop_column('template_exercises', 'weight')
    op.drop_column('template_exercises', 'reps')
    op.drop_column('template_exercises', 'sets')
    op.drop_column('template_exercises', 'stage_of_exercises')
    op.drop_column('template_exercises', 'exercise_name')
    op.drop_column('template_exercises', 'workout_day')
    op.add_column('exercises', sa.Column('target_muscle', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercises_target_musle'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_body_part'), table_name='exercises')
    op.alter_column('exercises', 'icon',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('exercises', 'target_musle')
    # ### end Alembic commands ###
