"""fix the connection between tables

Revision ID: 2dcfc2b9794e
Revises: bf9a2f0ff0d3
Create Date: 2026-01-16 20:58:02.917939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dcfc2b9794e'
down_revision: Union[str, Sequence[str], None] = 'bf9a2f0ff0d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # We must drop the index from workout_recommendations BEFORE creating it on user_workouts
    # because PostgreSQL requires index names to be unique within a schema.
    op.drop_index(op.f('idx_wr_user_created_at'), table_name='workout_recommendations')
    op.create_index('idx_user_created_at', 'workout_recommendations', ['user_id', 'created_at'], unique=False)
    
    op.drop_index(op.f('idx_uw_user_created_at'), table_name='user_workouts')
    op.create_index('idx_wr_user_created_at', 'user_workouts', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Same logic for downgrade: drop from user_workouts before recreating on workout_recommendations
    op.drop_index('idx_wr_user_created_at', table_name='user_workouts')
    op.create_index(op.f('idx_uw_user_created_at'), 'user_workouts', ['user_id', 'created_at'], unique=False)
    
    op.drop_index('idx_user_created_at', table_name='workout_recommendations')
    op.create_index(op.f('idx_wr_user_created_at'), 'workout_recommendations', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
