"""add address_id and creator_name columsn in user_workout_plans table and remove template_id

Revision ID: 35a8b84dca70
Revises: 49948b586213
Create Date: 2026-01-08 21:11:41.403201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a8b84dca70'
down_revision: Union[str, Sequence[str], None] = '49948b586213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workout_plans', sa.Column('address_id', sa.UUID(), nullable=False))
    op.add_column('user_workout_plans', sa.Column('creation_name', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('user_workout_plans_template_id_fkey'), 'user_workout_plans', type_='foreignkey')
    op.create_foreign_key(None, 'user_workout_plans', 'workout_templates', ['address_id'], ['id'])
    op.drop_column('user_workout_plans', 'template_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_workout_plans', sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_workout_plans', type_='foreignkey')
    op.create_foreign_key(op.f('user_workout_plans_template_id_fkey'), 'user_workout_plans', 'workout_templates', ['template_id'], ['id'])
    op.drop_column('user_workout_plans', 'creation_name')
    op.drop_column('user_workout_plans', 'address_id')
    # ### end Alembic commands ###
