"""mistakly remove is_active,create_at and update_at, so i add again in excerise table

Revision ID: 4332137f42a6
Revises: 729077d748f2
Create Date: 2026-01-01 18:47:25.724829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4332137f42a6'
down_revision: Union[str, Sequence[str], None] = '729077d748f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
