"""remove is_regular columns from user_workout_plans

Revision ID: 49948b586213
Revises: 62608cd5d6a7
Create Date: 2026-01-05 21:00:49.679844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49948b586213'
down_revision: Union[str, Sequence[str], None] = '62608cd5d6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_target_musle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_target_muscle'), 'exercises', ['target_muscle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_target_muscle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_target_musle'), 'exercises', ['target_muscle'], unique=False)
    # ### end Alembic commands ###
