"""add columns start, end and duration between them in session_exercises

Revision ID: 5b809db4e7ee
Revises: 2dcfc2b9794e
Create Date: 2026-01-18 18:26:17.218352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b809db4e7ee'
down_revision: Union[str, Sequence[str], None] = '2dcfc2b9794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercises', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('session_exercises', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('session_exercises', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_exercises', 'duration_minutes')
    op.drop_column('session_exercises', 'end_time')
    op.drop_column('session_exercises', 'start_time')
    # ### end Alembic commands ###
