"""fix the name of target_muscle in exercises table

Revision ID: 62608cd5d6a7
Revises: c7a306caf05c
Create Date: 2026-01-04 10:09:49.891747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62608cd5d6a7'
down_revision: Union[str, Sequence[str], None] = 'c7a306caf05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('target_musle', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_exercises_target_musle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_target_musle'), 'exercises', ['target_musle'], unique=False)
    op.drop_column('exercises', 'target_muscle')
    op.alter_column('template_exercises', 'reps',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template_exercises', 'reps',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('exercises', sa.Column('target_muscle', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercises_target_musle'), table_name='exercises')
    op.create_index(op.f('ix_exercises_target_musle'), 'exercises', ['target_muscle'], unique=False)
    op.drop_column('exercises', 'target_musle')
    # ### end Alembic commands ###
