"""add body_part, target, instruction, icon and difficulaty reason

Revision ID: 729077d748f2
Revises: fe79f978e8e1
Create Date: 2026-01-01 18:44:41.287767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729077d748f2'
down_revision: Union[str, Sequence[str], None] = 'fe79f978e8e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
