"""removed duplication in code of sql

Revision ID: bf9a2f0ff0d3
Revises: a1c07cff80a4
Create Date: 2026-01-10 20:34:09.585069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf9a2f0ff0d3'
down_revision: Union[str, Sequence[str], None] = 'a1c07cff80a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIRST: Drop foreign keys that reference scheduled_workouts BEFORE dropping tables
    op.drop_constraint('exercise_recommendations_scheduled_workout_id_fkey', 
                      'exercise_recommendations', type_='foreignkey')
    op.drop_constraint('workout_sessions_scheduled_workout_id_fkey', 
                      'workout_sessions', type_='foreignkey')
    
    # Create new tables
    op.create_table('user_workouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('target_muscle_groups', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uw_user_created_at', 'user_workouts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_workouts_name'), 'user_workouts', ['name'], unique=False)
    op.create_index(op.f('ix_user_workouts_user_id'), 'user_workouts', ['user_id'], unique=False)
    
    op.create_table('workout_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=50), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('target_muscle_groups', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=True),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('performance_metrics', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wr_user_created_at', 'workout_recommendations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_workout_recommendations_name'), 'workout_recommendations', ['name'], unique=False)
    op.create_index(op.f('ix_workout_recommendations_user_id'), 'workout_recommendations', ['user_id'], unique=False)
    
    op.create_table('user_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('workout_day', sa.String(length=50), nullable=True),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('exercise_name', sa.String(length=50), nullable=True),
    sa.Column('stage_of_exercises', sa.String(length=50), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('reps', sa.String(length=50), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_workout_id'], ['user_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_exercises_exercise_id'), 'user_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_exercises_user_workout_id'), 'user_exercises', ['user_workout_id'], unique=False)
    
    # Drop old tables (now safe because foreign keys are removed)
    op.drop_index('idx_scheduled_workout_order', table_name='scheduled_exercises')
    op.drop_index('ix_scheduled_exercises_scheduled_workout_id', table_name='scheduled_exercises')
    op.drop_table('scheduled_exercises')
    
    op.drop_index('idx_plan_scheduled_date', table_name='scheduled_workouts')
    op.drop_index('ix_scheduled_workouts_workout_plan_id', table_name='scheduled_workouts')
    op.drop_table('scheduled_workouts')
    
    # Modify exercise_recommendations table
    op.add_column('exercise_recommendations', sa.Column('template_id', sa.UUID(), nullable=False))
    op.add_column('exercise_recommendations', sa.Column('workout_day', sa.String(length=50), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('day_number', sa.Integer(), nullable=False))
    op.add_column('exercise_recommendations', sa.Column('exercise_name', sa.String(length=50), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('stage_of_exercises', sa.String(length=50), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('sequence_order', sa.Integer(), nullable=False))
    op.add_column('exercise_recommendations', sa.Column('sets', sa.Integer(), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('reps', sa.String(length=50), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('rest_seconds', sa.Integer(), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('exercise_recommendations', sa.Column('workout_type', sa.String(length=50), nullable=True))
    
    # Drop old index and create new ones
    op.drop_index('ix_exercise_recommendations_user_id', table_name='exercise_recommendations')
    op.create_index('ix_exercise_recommendations_exercise_id', 'exercise_recommendations', ['exercise_id'], unique=False)
    op.create_index('ix_exercise_recommendations_template_id', 'exercise_recommendations', ['template_id'], unique=False)
    
    # Drop old foreign keys and create new one
    op.drop_constraint('exercise_recommendations_model_id_fkey', 'exercise_recommendations', type_='foreignkey')
    op.drop_constraint('exercise_recommendations_user_id_fkey', 'exercise_recommendations', type_='foreignkey')
    op.create_foreign_key('exercise_recommendations_template_id_fkey', 'exercise_recommendations', 'workout_recommendations', ['template_id'], ['id'])
    
    # Drop old columns
    op.drop_column('exercise_recommendations', 'recommended_sets')
    op.drop_column('exercise_recommendations', 'confidence_score')
    op.drop_column('exercise_recommendations', 'model_id')
    op.drop_column('exercise_recommendations', 'reason')
    op.drop_column('exercise_recommendations', 'scheduled_workout_id')
    op.drop_column('exercise_recommendations', 'accepted')
    op.drop_column('exercise_recommendations', 'user_id')
    op.drop_column('exercise_recommendations', 'recommended_reps')
    op.drop_column('exercise_recommendations', 'recommended_weight_kg')
    
    # Modify user_feedback table
    op.drop_column('user_feedback', 'comments')
    op.drop_column('user_feedback', 'rating')
    
    # Modify user_workout_plans table
    op.add_column('user_workout_plans', sa.Column('template_id', sa.UUID(), nullable=True))
    op.add_column('user_workout_plans', sa.Column('ml_recommendation_id', sa.UUID(), nullable=True))
    op.add_column('user_workout_plans', sa.Column('user_workout_id', sa.UUID(), nullable=True))
    op.add_column('user_workout_plans', sa.Column('source_name', sa.String(length=10), nullable=True))
    op.create_index('idx_source_check', 'user_workout_plans', ['template_id', 'ml_recommendation_id', 'user_workout_id'], unique=False)
    op.create_foreign_key('user_workout_plans_template_id_fkey', 'user_workout_plans', 'workout_templates', ['template_id'], ['id'])
    op.create_foreign_key('user_workout_plans_ml_recommendation_id_fkey', 'user_workout_plans', 'workout_recommendations', ['ml_recommendation_id'], ['id'])
    op.create_foreign_key('user_workout_plans_user_workout_id_fkey', 'user_workout_plans', 'user_workouts', ['user_workout_id'], ['id'])
    op.drop_column('user_workout_plans', 'creator_name')
    op.drop_column('user_workout_plans', 'address_id')
    
    # Modify workout_sessions table
    op.add_column('workout_sessions', sa.Column('workout_plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key('workout_sessions_workout_plan_id_fkey', 'workout_sessions', 'user_workout_plans', ['workout_plan_id'], ['id'])
    op.drop_column('workout_sessions', 'scheduled_workout_id')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Recreate scheduled_workout_id column and foreign key
    op.add_column('workout_sessions', sa.Column('scheduled_workout_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint('workout_sessions_workout_plan_id_fkey', 'workout_sessions', type_='foreignkey')
    op.create_foreign_key('workout_sessions_scheduled_workout_id_fkey', 'workout_sessions', 'scheduled_workouts', ['scheduled_workout_id'], ['id'])
    op.drop_column('workout_sessions', 'workout_plan_id')
    
    # Restore user_workout_plans columns
    op.add_column('user_workout_plans', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('user_workout_plans', sa.Column('creator_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint('user_workout_plans_user_workout_id_fkey', 'user_workout_plans', type_='foreignkey')
    op.drop_constraint('user_workout_plans_ml_recommendation_id_fkey', 'user_workout_plans', type_='foreignkey')
    op.drop_constraint('user_workout_plans_template_id_fkey', 'user_workout_plans', type_='foreignkey')
    op.drop_index('idx_source_check', table_name='user_workout_plans')
    op.drop_column('user_workout_plans', 'source_name')
    op.drop_column('user_workout_plans', 'user_workout_id')
    op.drop_column('user_workout_plans', 'ml_recommendation_id')
    op.drop_column('user_workout_plans', 'template_id')
    
    # Restore user_feedback columns
    op.add_column('user_feedback', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_feedback', sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True))
    
    # Restore exercise_recommendations columns
    op.add_column('exercise_recommendations', sa.Column('recommended_weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('exercise_recommendations', sa.Column('recommended_reps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('exercise_recommendations', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('exercise_recommendations', sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('exercise_recommendations', sa.Column('scheduled_workout_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('exercise_recommendations', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercise_recommendations', sa.Column('model_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('exercise_recommendations', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('exercise_recommendations', sa.Column('recommended_sets', sa.INTEGER(), autoincrement=False, nullable=True))
    
    # Restore exercise_recommendations foreign keys and indexes
    op.drop_constraint('exercise_recommendations_template_id_fkey', 'exercise_recommendations', type_='foreignkey')
    op.create_foreign_key('exercise_recommendations_scheduled_workout_id_fkey', 'exercise_recommendations', 'scheduled_workouts', ['scheduled_workout_id'], ['id'])
    op.create_foreign_key('exercise_recommendations_user_id_fkey', 'exercise_recommendations', 'users', ['user_id'], ['id'])
    op.create_foreign_key('exercise_recommendations_model_id_fkey', 'exercise_recommendations', 'ml_models', ['model_id'], ['id'])
    op.drop_index('ix_exercise_recommendations_template_id', table_name='exercise_recommendations')
    op.drop_index('ix_exercise_recommendations_exercise_id', table_name='exercise_recommendations')
    op.create_index('ix_exercise_recommendations_user_id', 'exercise_recommendations', ['user_id'], unique=False)
    
    # Drop new columns from exercise_recommendations
    op.drop_column('exercise_recommendations', 'workout_type')
    op.drop_column('exercise_recommendations', 'notes')
    op.drop_column('exercise_recommendations', 'rest_seconds')
    op.drop_column('exercise_recommendations', 'weight')
    op.drop_column('exercise_recommendations', 'reps')
    op.drop_column('exercise_recommendations', 'sets')
    op.drop_column('exercise_recommendations', 'sequence_order')
    op.drop_column('exercise_recommendations', 'stage_of_exercises')
    op.drop_column('exercise_recommendations', 'exercise_name')
    op.drop_column('exercise_recommendations', 'day_number')
    op.drop_column('exercise_recommendations', 'workout_day')
    op.drop_column('exercise_recommendations', 'template_id')
    
    # Recreate old tables
    op.create_table('scheduled_workouts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workout_plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workout_plan_id'], ['user_workout_plans.id'], name='scheduled_workouts_workout_plan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduled_workouts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_scheduled_workouts_workout_plan_id', 'scheduled_workouts', ['workout_plan_id'], unique=False)
    op.create_index('idx_plan_scheduled_date', 'scheduled_workouts', ['workout_plan_id', 'scheduled_date'], unique=False)
    
    op.create_table('scheduled_exercises',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scheduled_workout_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sequence_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planned_sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_reps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('planned_rest_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name='scheduled_exercises_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['scheduled_workout_id'], ['scheduled_workouts.id'], name='scheduled_exercises_scheduled_workout_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='scheduled_exercises_pkey')
    )
    op.create_index('ix_scheduled_exercises_scheduled_workout_id', 'scheduled_exercises', ['scheduled_workout_id'], unique=False)
    op.create_index('idx_scheduled_workout_order', 'scheduled_exercises', ['scheduled_workout_id', 'sequence_order'], unique=False)
    
    # Drop new tables
    op.drop_index('ix_user_exercises_user_workout_id', table_name='user_exercises')
    op.drop_index('ix_user_exercises_exercise_id', table_name='user_exercises')
    op.drop_table('user_exercises')
    
    op.drop_index('ix_workout_recommendations_user_id', table_name='workout_recommendations')
    op.drop_index('ix_workout_recommendations_name', table_name='workout_recommendations')
    op.drop_index('idx_wr_user_created_at', table_name='workout_recommendations')
    op.drop_table('workout_recommendations')
    
    op.drop_index('ix_user_workouts_user_id', table_name='user_workouts')
    op.drop_index('ix_user_workouts_name', table_name='user_workouts')
    op.drop_index('idx_uw_user_created_at', table_name='user_workouts')
    op.drop_table('user_workouts')
    
    # ### end Alembic commands ###