"""turn datatype of reps int into string in template_exercises  table due to  sec present for some exercise

Revision ID: c7a306caf05c
Revises: 1d4569bc6281
Create Date: 2026-01-04 09:52:48.613980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7a306caf05c'
down_revision: Union[str, Sequence[str], None] = '1d4569bc6281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_templates_backup_1767358588')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_templates_backup_1767358588',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_muscle_groups', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('workout_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
