"""transfer weight_km cols from BodyMetric to UserProfile table

Revision ID: fe79f978e8e1
Revises: eaebad4b8891
Create Date: 2026-01-01 17:35:05.550665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe79f978e8e1'
down_revision: Union[str, Sequence[str], None] = 'eaebad4b8891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_measurements', 'weight_kg')
    op.add_column('user_profiles', sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'weight_kg')
    op.add_column('body_measurements', sa.Column('weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
